### ISSUE TITLE
Quizzes Page

### ISSUE THREAD

**Issue by jonathanmajh** [SssWind/Learn-Darklight#1]
While checking into my PD course today I've notice that the header of the quiz page isn't scroll able. So the area which shows the quiz is actually really small, is it possible for you to change this?

https://imgur.com/a/RjNJWpp

**Comment by zijian-shao** [comment]
I currently don't have any quizzes ongoing. Could you please email me the html code of that quiz page so that I can analyze the html structure? You might need to delete some personal info from the code. Thanks.
sam.zj.shao@gmail.com
