### ISSUE TITLE
Firefox Popup in Overflow

### ISSUE THREAD

**Issue by GeraldNDA** [SssWind/Learn-Darklight#2]
The popup looks fine when used in the toolbar like normal but if I move it into the overflow, then some of it gets cut off.

I'm running FF/61.0.1
**Popup in Toolbar**
![learndarklightbase](https://user-images.githubusercontent.com/11413630/42917873-6ab7a62a-8ad9-11e8-8ae4-6156b121da8e.png)
**Popup in Toolbar Overflow**
![learndarklightoverflow](https://user-images.githubusercontent.com/11413630/42917877-6cdafae2-8ad9-11e8-9a0c-8d4d99d6ac88.png)

**Comment by zijian-shao** [comment]
Thanks for you feedback. I've uploaded a new version 1.4.7 to Firefox addons. You may wait for auto update or update manually.
