### ISSUE TITLE
Class cards fail to load

### ISSUE THREAD

**Issue by JeffreyCA** [SssWind/Learn-Darklight#3]
Recently the home page on LEARN fails to load.

Screenshot:
<img width="816" alt="Screen Shot 2020-10-23 at 10 54 17 AM" src="https://user-images.githubusercontent.com/9157833/97019284-24785480-151e-11eb-8346-b45d95961352.png">

Error in Console:

```
init_idle.js:1219 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at init_idle.js:1219
    at NodeList.forEach (<anonymous>)
    at init_idle.js:1215
```

<img width="778" alt="Screen Shot 2020-10-23 at 10 52 56 AM" src="https://user-images.githubusercontent.com/9157833/97019214-0e6a9400-151e-11eb-9bce-789f9ccd670a.png">

**Comment by zijian-shao** [comment]
Thanks for your feedback. This issue has been fixed. 
I've uploaded a new version (3.0.21) to the Chrome/Edge/Firefox store. The extension review process will take 1 to 2 days based on past experience.
