### ISSUE TITLE
Learn Just stays in loading page with extension on 

### ISSUE THREAD

**Issue by mathgod123** [SssWind/Learn-Darklight#4]
When the extension is on, the homepage of learn just stays in loading screen. Once I turn the extension off, the learn homepage shows up! 
Please let me know once this is fixed as my friend as the same issue.

**Comment by zijian-shao** [comment]
Thanks for your feedback. This issue has been fixed.
I've uploaded a new version (3.0.21) to the Chrome/Edge/Firefox store. The extension review process will take 1 to 2 days based on past experience.

**Comment by Awbmilne** [comment]
Same issue, Looking forward to the fix @SssWind 👍

**Comment by zijian-shao** [comment]
Thanks for your patience. The new version is now published to the store. @mathgod123 @Awbmilne

**Comment by Awbmilne** [comment]
Issue Fixed! Thanks @SssWind
